### PR TITLE
Update README.md to point to correct repo URL

### PR DESCRIPTION
**Pull request by pavellishin**

### CODE REVIEW

**Comment by shaunburdick** [comment]
This never really ended up going anywhere (unfortunately) so there is no point in updating anything :-/

**Comment by pavellishin** [comment]
Is it playable at all? And do you have any interest in reviving it?

**Comment by shaunburdick** [comment]
Not really, I think I left off after dice rolling. I just got busy and moved on to other things. It's one of those "someday" projects.

**Comment by pavellishin** [comment]
Aw, man, I'm sorry to hear that. It sounded like a really great project, and a slack I'm in was all excited about it. Let me know if you ever want to work on this again; I'm poking around trying to write an Slack version of idlerpg at the moment, and this actually looks like it might be easier.

**Pull request closed without merging**
